### ISSUE TITLE
strcpy_chk: symbol not found

### ISSUE THREAD

**Issue by Lilja** [tursodatabase/libsql-client-ts#180]
I'm trying to package my API into a docker image, using `node:20-alpine`.

Running my app leads to 

```
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] node:internal/modules/cjs/loader:1473
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] return process.dlopen(module, path.toNamespacedPath(filename));
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] ^
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] Error: Error relocating /app/node_modules/@libsql/linux-x64-musl/index.node: __strcpy_chk: symbol not found
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] at Module._load (node:internal/modules/cjs/loader:1023:12)
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] at Module.require (node:internal/modules/cjs/loader:1235:19)
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] at require (node:internal/modules/helpers:176:18)
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] at Object.<anonymous> (/app/node_modules/libsql/index.js:41:24)
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] at Module._compile (node:internal/modules/cjs/loader:1376:14)
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] at Module.load (node:internal/modules/cjs/loader:1207:32)
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] at Module._load (node:internal/modules/cjs/loader:1023:12) {
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] code: 'ERR_DLOPEN_FAILED'
2024-02-17T11:15:12.739 app[080e513b19e298] ams [info] } 
```

It might be an issue with glibc/musl. [See this issue](https://github.com/serialport/node-serialport/issues/682)

Do the libsql team have an opinion of what type of distribution I should use?

<details>

<summary>Dockerfile</summary>

```Dockerfile
FROM node:20-alpine as base

WORKDIR /app
COPY ./dist /app/dist

ARG GIT_SHA
ENV GIT_REVISION=$GIT_SHA

RUN npm install @libsql/client

EXPOSE 4000
CMD [ "node", "--no-warnings=ExperimentalWarning", "dist/index.js" ]
```

</details>

**Comment by lovell** [comment]
I've just hit this when upgrading from v0.2.0 to v0.3.x.

It looks like the `@libsql/linux-x64-musl/index.node` binaries since v0.3.1 might have been built against glibc rather than musl.

v0.2.0:
```
# ldd node_modules/@libsql/linux-x64-musl/index.node
	/lib/ld-musl-x86_64.so.1 (0x7f2fdf705000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f2fdf052000)
	libc.so => /lib/ld-musl-x86_64.so.1 (0x7f2fdf705000)
```

v0.3.1:
```
# ldd node_modules/@libsql/linux-x64-musl/index.node 
	/lib/ld-musl-x86_64.so.1 (0x7f3343052000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7f33423d0000)
	libc.so => /lib/ld-musl-x86_64.so.1 (0x7f3343052000)
Error relocating node_modules/@libsql/linux-x64-musl/index.node: __strcpy_chk: symbol not found
Error relocating node_modules/@libsql/linux-x64-musl/index.node: __memcpy_chk: symbol not found
Error relocating node_modules/@libsql/linux-x64-musl/index.node: __memset_chk: symbol not found
Error relocating node_modules/@libsql/linux-x64-musl/index.node: fcntl64: symbol not found
```

v0.3.2:
```
# ldd node_modules/@libsql/linux-x64-musl/index.node 
	/lib/ld-musl-x86_64.so.1 (0x7fb7d2869000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fb7d1be1000)
	libc.so => /lib/ld-musl-x86_64.so.1 (0x7fb7d2869000)
Error relocating node_modules/@libsql/linux-x64-musl/index.node: __strcpy_chk: symbol not found
Error relocating node_modules/@libsql/linux-x64-musl/index.node: fcntl64: symbol not found
Error relocating node_modules/@libsql/linux-x64-musl/index.node: __memcpy_chk: symbol not found
Error relocating node_modules/@libsql/linux-x64-musl/index.node: __memset_chk: symbol not found
Error relocating node_modules/@libsql/linux-x64-musl/index.node: fcntl64: symbol not found
```

Checking the commit history I suspect https://github.com/tursodatabase/libsql-js/commit/e325e782a029f114aad8b1b85a675ea90152ec9c that introduced https://github.com/dherman/neon-rs/commit/9903c9512207312230db92683b550f04b6a23ef0 is a possible cause.

**Comment by yrke** [comment]
As a workaround we downgrading from `v5.x` to `v0.4.3` tested to work with `node:18-alpine` and `node:20-alpine` (at least for now)

**Comment by penberg** [comment]
Thanks for looking into this, @lovell! Unfortunately, the `@neon-rs/cli` bump was not related to the problem. Instead it's this libsql issue related to the new encryption feature: https://github.com/tursodatabase/libsql/issues/1155

**Comment by lovell** [comment]
Thanks for the updates, the `fcntl64: symbol not found` error remains with the new version when testing with latest Alpine Edge:
```
# cat node_modules/@libsql/linux-x64-musl/package.json | grep version
  "version": "0.3.9",

# ldd node_modules/@libsql/linux-x64-musl/index.node 
	/lib/ld-musl-x86_64.so.1 (0x76c8197f6000)
	libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x76c818f42000)
	libc.so => /lib/ld-musl-x86_64.so.1 (0x76c8197f6000)
Error relocating node_modules/@libsql/linux-x64-musl/index.node: fcntl64: symbol not found
```

The `fcntl64` symbol is glibc-only and was introduced in glibc 2.28.

**Comment by RA9** [comment]
@lovell is the issue fixed?

**Comment by lovell** [comment]
@RA9 This problem remains and now there are duplicate reports appearing e.g. https://github.com/tursodatabase/libsql-js/issues/91

The summary is that the `@libsql/linux-x64-musl` package provided from v0.3.1 onwards, including the latest v0.3.10, does not work on musl-based systems.

**Comment by ruohki** [comment]
Ran into this problem while trying to build a astro application with the db integration. Wont build using node:lts-alpine

```
#0 2.037 node:internal/modules/cjs/loader:1473
#0 2.037   return process.dlopen(module, path.toNamespacedPath(filename));
#0 2.037                  ^
#0 2.037
#0 2.037 Error: Error relocating /app/node_modules/@libsql/linux-x64-musl/index.node: fcntl64: symbol not found
#0 2.037     at Module._extensions..node (node:internal/modules/cjs/loader:1473:18)
#0 2.037     at Module.load (node:internal/modules/cjs/loader:1207:32)
#0 2.037     at Module._load (node:internal/modules/cjs/loader:1023:12)
#0 2.037     at Module.require (node:internal/modules/cjs/loader:1235:19)
#0 2.037     at require (node:internal/modules/helpers:176:18)
#0 2.037     at Object.<anonymous> (/app/node_modules/libsql/index.js:42:5)
#0 2.037     at Module._compile (node:internal/modules/cjs/loader:1376:14)
#0 2.037     at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
#0 2.037     at Module.load (node:internal/modules/cjs/loader:1207:32)
#0 2.037     at Module._load (node:internal/modules/cjs/loader:1023:12) {
#0 2.037   code: 'ERR_DLOPEN_FAILED'
#0 2.037 }
#0 2.037
#0 2.037 Node.js v20.11.1
```

**Comment by flexchar** [comment]
@lovell does it mean we (Alpine users) must stick to v0.3.0 version?

**Comment by lovell** [comment]
@flexchar That is my understanding, yes, but I'm only the messenger here. You'll need to ask one of the maintainers about the future possible re-introduction of support for musl-based Linux.

**Comment by IsaiahByDayah** [comment]
Hey @penberg, should this issue could be reopened? It doesn’t seem like the above proposed fix actually solved whatever the issue is for musl builds :/

**Comment by LukaGiorgadze** [comment]
Same problem.
`/node_modules/@libsql/linux-x64-musl/index.node: fcntl64: symbol not found`

node 18 alpine.

**Comment by steschi** [comment]
@LukaGiorgadze not sure if it works for your setup, but I am using yarn v3 and as such can ensure I am using a version of libsql that works with alpine by adding this to the root package.json of my monorepo.

```json
"resolutions": {
    "@libsql/linux-x64-musl@npm:0.3.15": "0.2.0"
},
  ```
  
  For npm-users i guess `overrides` should be the equivalent -> https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides

**Comment by MikeTeddyOmondi** [comment]
When is the release for this issue scheduled??
@penberg

**Comment by LukaGiorgadze** [comment]
> @LukaGiorgadze not sure if it works for your setup, but I am using yarn v3 and as such can ensure I am using a version of libsql that works with alpine by adding this to the root package.json of my monorepo.
> 
> ```json
> "resolutions": {
>     "@libsql/linux-x64-musl@npm:0.3.15": "0.2.0"
> },
> ```
> 
> For npm-users i guess `overrides` should be the equivalent -> https://docs.npmjs.com/cli/v10/configuring-npm/package-json#overrides

Tried, but did not work :/

**Comment by MikeTeddyOmondi** [comment]
@LukaGiorgadze 
thats true .....

**Comment by jeremybarbet** [comment]
Can this be reopened, because this issue is still happening

**Comment by jeremybarbet** [comment]
FYI, `node-sqlite3` had the same [issue](https://github.com/TryGhost/node-sqlite3/issues/1576) and [the fix](https://github.com/TryGhost/node-sqlite3/commit/290d34f00dd24445b045d79622d2cf866a1d44fe) for it

**Comment by erehwonmi** [comment]
Issue still persists up to this date

**Comment by brunodasilvalenga** [comment]
Same here, getting the error in a nextjs app usign the @libsql/client version 0.6.0

**Comment by erehwonmi** [comment]
If some of you are using the Alpine distribution of Node for docker-izing an app with Libsql, I suggest migrating to the Bookworm distribution that fixed my issue and I can now use the latest version of libsql client.

**Comment by jeremybarbet** [comment]
It's a workaround, but not a solution. Bookworm, bullseye or even distroless images work but are consuming more RAM compare to Alpine (15/20% more). In environment where you want to control cost on memory usage, Alpine is still the most optimised.

PS: You can probably use `slim` rather than the whole `bookworm` as well

**Comment by ahtcx** [comment]
I'm getting this currently with `libsql@0.4.1` and the `alpine:latest` Docker image.

**Comment by jonathannorris** [comment]
We are also getting this with the `node:22.7-alpine3.20` docker image

**Comment by ahtcx** [comment]
I resolved it by overriding `@libsql/linux-x64-musl`'s version to be `0.2.0` as specified above, here's how I did this with pnpm.

```
{
	// ...
	"pnpm": {
		"overrides": {
			"@libsql/linux-x64-musl": "0.2.0"
		}
	}
}
```

**Comment by LucioFranco** [comment]
I did some digging it looks like there were some larger issues with our Rust/C code that we built the js library (which TS uses). This PR should fix those issues and subsequent TS/Js issues https://github.com/tursodatabase/libsql/pull/1724

**Comment by switz** [comment]
Still seeing this error on the latest version
