### ISSUE TITLE
Always getting status 405

### ISSUE THREAD

**Issue by Creative-Difficulty** [tursodatabase/libsql-client-ts#223]
<img width="970" alt="Bildschirmfoto 2024-06-14 um 12 28 31" src="https://github.com/tursodatabase/libsql-client-ts/assets/80907917/9d345680-317b-4872-b19f-5703219ca83e">
Since today morning, i have only been getting this error. Even the simplest inserts fail. However drizzle migrations are working for some reason, so the credentials are correct. Yesterday my setup was working, so i believe this error isn't on my end

**Comment by Creative-Difficulty** [comment]
@penberg @honzasp @giovannibenussi

**Comment by Creative-Difficulty** [comment]
fixed in https://ptb.discord.com/channels/933071162680958986/1249964350437851156

**Comment by Creative-Difficulty** [comment]
<img width="1133" alt="Bildschirmfoto 2024-06-23 um 14 01 48" src="https://github.com/tursodatabase/libsql-client-ts/assets/80907917/ce70768a-f536-46cd-8d2c-f8e9f53fc7d1">

**Comment by giovannibenussi** [comment]
Hey, we've seen some issues on different environments, for example, when you set the database URL and token using something like `import.meta` or similar.

I'm glad that you were able to solve this issue! This solution helps us to understand this issue better, thanks for sharing your it!

**Comment by Creative-Difficulty** [comment]
This is an issue with bun's fetch override. It is fixed by either not using `bun --bun run dev` (just `bun run dev`, which respects the shebangs in scripts and executes with node most of the time). Thanks for the feedback! Glad i could help!

**Comment by Myster987** [comment]
I found an even better solution without the need for additional libraries
`import { DB_URL } from '$env/static/private';
import { drizzle } from 'drizzle-orm/libsql';
import { createClient } from '@libsql/client';

const client = createClient({ url: DB_URL, fetch: async (req: Request) => {
    return fetch(req.url, req);    
} });

export const db = drizzle(client);`
The main issue is this [one](https://github.com/oven-sh/bun/issues/11381). For some reason bun doesn't accept raw Request object and in order for it to work the url is needed, so you use url from request object itself. I tested it with all methods (select, insert, delete, etc) and it works fine. I hope it helps
