### ISSUE TITLE
client is breaking with newer node versions

### ISSUE THREAD

**Issue by avinassh** [tursodatabase/libsql-client-ts#240]
A user reports: 

> my query never completes when i query more than 100 rows.

![image](https://github.com/user-attachments/assets/38eb3dc8-8e1f-432f-b6d6-40f34cdf6563)

> it apparently happens in the "decodeResponse" function in the hrana-client

> it's related to the node version..
20.11.1 works
20.15.1 does not work
22.4.1 is also broken

reported here: https://discord.com/channels/933071162680958986/1154725980183732224/1262016247864885395

**Comment by fiws** [comment]
seems to be fixed with never libsql version.

**Comment by notrab** [comment]
I'm not able to replicate this. If it continues to be an issue for others, let's reopen.
