### ISSUE TITLE
Not work with latest version of drizzle-orm

### ISSUE THREAD

**Issue by 1qh** [tursodatabase/libsql-client-ts#274]
#205 reappear, following docs from [Drizzle](https://orm.drizzle.team/docs/connect-turso)

**Comment by thibaultleouay** [comment]
This might be drizzle related it works with 0.34.1 but breaks with 0.35.0

**Comment by notrab** [comment]
Drizzle informed me that there is an issue they're working on in regards to the `connection` property of `drizzle` in 0.35.

I did actually manage to get `0.35` working for me, but only if I pass the `client` instance to `drizzle(client)` myself.
