### ISSUE TITLE
bugs in README example?

### ISSUE THREAD

**Issue by jwetzell** [tursodatabase/libsql-client-ts#278]
Looks like the README has a couple bugs for the quickstart example.

- `client.batch....` - `client` does not exist this should probably be `turso.batch`
- the insert statement errors out because of column count mismatch
  - should probably be `INSERT INTO users(name) VALUES (?)`
  - or `INSERT INTO users VALUES (NULL, ?)`

**Comment by notrab** [comment]
@giovannibenussi these were fixed recently, right?

**Comment by jwetzell** [comment]
looks fixed now

**Comment by notrab** [comment]
Awesome, thanks @jwetzell 🚀
